// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	GithubID        string
	NameWithOwner   string
	Description     pgtype.Text
	Stars           int32
	PrimaryLanguage pgtype.Text
	IsArchived      bool
}

type Star struct {
	GithubID string
	Stars    int32
	Time     pgtype.Timestamptz
}

type StarsDaily struct {
	Bucket        interface{}
	GithubID      string
	StarsEarliest interface{}
	StarsLatest   interface{}
}

type StarsTrendDaily struct {
	GithubID        pgtype.Text
	NameWithOwner   pgtype.Text
	PrimaryLanguage pgtype.Text
	Description     pgtype.Text
	StarsToday      interface{}
	StarsPrev       interface{}
	StarsDiff       int32
}

type StarsTrendMonthly struct {
	GithubID        pgtype.Text
	NameWithOwner   pgtype.Text
	PrimaryLanguage pgtype.Text
	Description     pgtype.Text
	StarsToday      interface{}
	StarsPrev       interface{}
	StarsDiff       int32
}

type StarsTrendWeekly struct {
	GithubID        pgtype.Text
	NameWithOwner   pgtype.Text
	PrimaryLanguage pgtype.Text
	Description     pgtype.Text
	StarsToday      interface{}
	StarsPrev       interface{}
	StarsDiff       int32
}

type TempRepository struct {
	GithubID        string
	NameWithOwner   string
	Description     pgtype.Text
	Stars           int32
	PrimaryLanguage pgtype.Text
	IsArchived      bool
}
