// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	GithubID        string
	NameWithOwner   string
	Description     pgtype.Text
	Stars           int32
	PrimaryLanguage pgtype.Text
}

type Star struct {
	GithubID string
	Stars    int32
	Time     pgtype.Timestamptz
}

type TempRepository struct {
	GithubID        string
	NameWithOwner   string
	Description     pgtype.Text
	Stars           int32
	PrimaryLanguage pgtype.Text
}
